name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liAgR6oH56kA40re
"
GITHUB_OWNER = "hdgzsq"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://943bb3fe.navsphere-cn6.pages.dev//api/auth"
NEXT_PUBLIC_API_URL="https://943bb3fe.navsphere-cn6.pages.dev/"

